import { createClient } from "@/lib/supabase/client";
export type ProductionStatus="queued"|"in_progress"|"quality_check"|"ready"|"completed"|"cancelled";
export type ProductionRun={id:string;batch_id:string|null;product_id:string|null;order_id:string|null;status:ProductionStatus;planned_quantity:number|null;produced_quantity:number|null;unit:string|null;started_at:string|null;completed_at:string|null;notes:string|null;created_at:string;updated_at:string;product:{name:string;slug:string}|null;batch:{batch_code:string;production_date:string|null;status:string}|null;order:{order_number:string|null;status:string;total:number}|null};
export type Option={id:string;name:string;slug?:string;status?:string};
export type OrderOption={id:string;order_number:string|null;status:string};
const db=()=>createClient();
export async function getProductionOperations(){const [r,p,o,i]=await Promise.all([db().from("production_runs").select("id,batch_id,product_id,order_id,status,planned_quantity,produced_quantity,unit,started_at,completed_at,notes,created_at,updated_at,product:products(name,slug),batch:batches(batch_code,production_date,status),order:orders(order_number,status,total)").order("created_at",{ascending:false}),db().from("products").select("id,name,slug").eq("active",true).order("name"),db().from("orders").select("id,order_number,status").in("status",["confirmed","preparing","pressing","ready"]).order("created_at",{ascending:false}).limit(100),db().from("inventory_items").select("id,ingredient_id,quantity,unit,reorder_level,ingredient:ingredients(name)").order("quantity")]);if(r.error)throw r.error;if(p.error)throw p.error;if(o.error)throw o.error;if(i.error)throw i.error;return{runs:(r.data??[]) as unknown as ProductionRun[],products:(p.data??[]) as Option[],orders:(o.data??[]) as OrderOption[],inventory:i.data??[]};}
export async function createProductionRun(input:{productId:string;orderId?:string|null;plannedQuantity?:number|null;unit?:string|null;notes?:string|null}){const {data:u}=await db().auth.getUser();const {data,error}=await db().from("production_runs").insert({product_id:input.productId,order_id:input.orderId||null,planned_quantity:input.plannedQuantity??null,unit:input.unit||"bottles",notes:input.notes||null,created_by:u.user?.id||null}).select().single();if(error)throw error;return data;}
export async function advanceProductionRun(id:string,status:ProductionStatus){const {data,error}=await db().rpc("advance_production_run",{p_production_run_id:id,p_status:status});if(error)throw error;return data;}
export async function consumeInventoryForProduction(id:string,itemId:string,quantity:number,unit:string){const {data,error}=await db().rpc("consume_inventory_for_production",{p_production_run_id:id,p_inventory_item_id:itemId,p_quantity:quantity,p_unit:unit});if(error)throw error;return data;}
export async function createBatchFromProduction(id:string,code:string,date:string,useBy?:string,notes?:string){const {data,error}=await db().rpc("create_production_batch",{p_production_run_id:id,p_batch_code:code,p_production_date:date,p_use_by_date:useBy||null,p_notes:notes||null});if(error)throw error;return data as string;}
export async function getConsumption(id:string){const {data,error}=await db().from("production_consumption").select("*,ingredient:ingredients(name),supplier:suppliers(name),inventory_lot:inventory_lots(lot_code,quantity_received,quantity_remaining)").eq("production_run_id",id).order("created_at",{ascending:false});if(error)throw error;return data??[];}
